# Generated by Django 2.2.2 on 2019-06-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oslive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(default=None, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
