# Generated by Django 2.2.2 on 2019-06-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oslive', '0002_anexo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
