# Generated by Django 2.2.2 on 2019-06-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oslive', '0003_auto_20190613_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='alternativaA',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alternativaB',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alternativaC',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='alternativaD',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='enunciado',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
